services:
  redis:
    image: redis:7.4.2
    ports:
      - "9951:6379"
    volumes:
      - "./redis:/data"
    environment:
      - REDIS_PASSWORD=pass
      - REDIS_USER=user
      - REDIS_USER_PASSWORD=pass
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping" ]
      interval: 45s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
